
import React from "react";
import { Switch, BrowserRouter as Router, Route } from "react-router-dom";
import IPadPro111 from "./components/IPadPro111";
import Desktop1 from "./components/Desktop1";
import IPhoneSE1 from "./components/IPhoneSE1";

function App() {
  return (
    <Router>
      <Switch>
        <Route path="/ipad-pro-11-1">
          <IPadPro111 {...iPadPro111Data} />
        </Route>
        <Route path="/:path(|desktop-1)">
          <Desktop1 {...desktop1Data} />
        </Route>
        <Route path="/iphone-se-1">
          <IPhoneSE1 {...iPhoneSE1Data} />
        </Route>
      </Switch>
    </Router>
  );
}

export default App;
const heroSectionData = {
    x20211126_115930: "/img/20211126-115930-3@1x.png",
    xolodaoNft: "/img/xolodao-nft-3@1x.png",
    frame52: "/img/frame-52-2@2x.png",
    joinDiscord: "JOIN DISCORD",
    frame53: "/img/frame-53-1@2x.png",
};

const desktop1Data = {
    xolodao: "/img/xolodao@2x.png",
    about: "/img/about@2x.png",
    roadmap: "/img/roadmap-2@2x.png",
    collection: "/img/collection-2@2x.png",
    dao: "/img/dao@2x.png",
    faq: "/img/faq-2@2x.png",
    frame143: "/img/frame-143@2x.png",
    overlapGroup: "/img/ellipse-16-2@2x.png",
    butterflyNft1: "/img/butterfly-nft-1-1@1x.png",
    xoloSugarSkull01: "/img/xolo-sugar-skull-01-2@2x.png",
    aboutUs: "/img/about-us-1@2x.png",
    weAreNotJustAnot: <>We are not just another NFT Project!! We aim to achieve 3 main goals with our community.<br />               1. Impact <br />               2. Value <br />               3. Connection <br />We choose the Xolo Dog to be our emblem as it is the guide between worlds. We aim to connect the physical and the digital world with our community and our actions. Read the Roadmap to find out and Join the XoloDAO</>,
    roadmap2: "/img/roadmap-1@2x.png",
    skull_Roadmap1: "/img/skull-roadmap-1-1@2x.png",
    frame74: "/img/frame-74-1@1x.png",
    skull_Roadmap3: "/img/skull-roadmap-1-1@2x.png",
    frame76: "/img/frame-76-1@1x.png",
    xoloSugarSkull012: "/img/xolo-sugar-skull-01-3@2x.png",
    rectangle17: "/img/rectangle-17-1@2x.png",
    rectangle18: "/img/rectangle-18-1@2x.png",
    rectangle19: "/img/rectangle-19-1@1x.png",
    frame73: "/img/frame-73-1@1x.png",
    skull_Roadmap2: "/img/skull-roadmap-1-1@2x.png",
    frame75: "/img/frame-75-1@1x.png",
    skull_Roadmap4: "/img/skull-roadmap-1-1@2x.png",
    frame77: "/img/frame-77-1@1x.png",
    collection2: "/img/collection-1@2x.png",
    dogs11: "/img/dogs1-1-1@1x.png",
    weWillBeShowcasingSoonOurCollection: "/img/we-will-be-showcasing-soon-our-collection--join-our-discord-to-s-1@1x.png",
    overlapGroup6: "/img/20211126-120014-1@1x.png",
    rectangle57: "/img/rectangle-57-1@2x.png",
    rectangle58: "/img/rectangle-58-1@2x.png",
    title: "Days",
    x88: "/img/88-7@2x.png",
    rectangle59: "/img/rectangle-59-1@2x.png",
    rectangle60: "/img/rectangle-60-1@2x.png",
    hours: "Hours",
    x882: "/img/88-6@2x.png",
    rectangle61: "/img/rectangle-61-1@2x.png",
    rectangle62: "/img/rectangle-62-1@2x.png",
    minuts: "Minuts",
    x883: "/img/88-5@2x.png",
    rectangle63: "/img/rectangle-63-1@2x.png",
    rectangle64: "/img/rectangle-64-1@2x.png",
    seconds: "Seconds",
    x884: "/img/88-4@2x.png",
    time8GmtGlobalMetaverseTime: "time: 8 GMT (Global Metaverse Time )",
    frame52: "/img/frame-52-3@2x.png",
    ellipse16: "/img/ellipse-16-2@2x.png",
    whenIsTheDrop: "When is the drop?",
    loremIpsumIsSimpl: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    name: "Will there be a comunity fund?",
    x4534: "/img/-@2x.png",
    whenIsTheDrop2: "When is the drop?",
    name2: "Will the price increase?",
    x4545: "/img/-@2x.png",
    name3: "Will there be a comunity fund?",
    x4548: "/img/-@2x.png",
    faq2: "/img/faq-1@2x.png",
    footer: "/img/footer-1@1x.png",
    heroSectionProps: heroSectionData,
};

const iPadPro111Data = {
    menu: "/img/menu@1x.png",
    x20211126_115930: "/img/20211126-115930@2x.png",
    xolodaoNft: "/img/xolodao-nft@2x.png",
    frame52: "/img/frame-52@2x.png",
    joinDiscord: "JOIN DISCORD",
    frame53: "/img/frame-53@2x.png",
    weAreNotJustAnot: <>We are not just another NFT Project!! We aim to achieve 3 main goals with our community.<br />               1. Impact <br />               2. Value <br />               3. Connection <br />We choose the Xolo Dog to be our emblem as it is the guide between worlds. We aim to connect the physical and the digital world with our community and our actions. Read the Roadmap to find out and Join the XoloDAO</>,
    aboutUs: "/img/about-us@2x.png",
    overlapGroup: "/img/ellipse-16@2x.png",
    butterflyNft1: "/img/butterfly-nft-1@2x.png",
    xoloSugarSkull01: "/img/xolo-sugar-skull-01@2x.png",
    roadmap: "/img/roadmap@2x.png",
    skull_Roadmap1: "/img/skull-roadmap-1@2x.png",
    frame74: "/img/frame-74@2x.png",
    skull_Roadmap3: "/img/skull-roadmap-3@2x.png",
    frame76: "/img/frame-76@2x.png",
    xoloSugarSkull012: "/img/xolo-sugar-skull-01-1@2x.png",
    rectangle17: "/img/rectangle-17@2x.png",
    rectangle18: "/img/rectangle-18@2x.png",
    rectangle19: "/img/rectangle-19@2x.png",
    frame73: "/img/frame-73@2x.png",
    skull_Roadmap2: "/img/skull-roadmap-2@2x.png",
    frame75: "/img/frame-75@2x.png",
    skull_Roadmap4: "/img/skull-roadmap-4@2x.png",
    frame77: "/img/frame-77@2x.png",
    collection: "/img/collection@2x.png",
    dogs11: "/img/dogs1-1@1x.png",
    weWillBeShowcasingSoonOurCollection: "/img/we-will-be-showcasing-soon-our-collection--join-our-discord-to-s@2x.png",
    overlapGroup6: "/img/20211126-120014@1x.png",
    rectangle57: "/img/rectangle-57@2x.png",
    rectangle58: "/img/rectangle-58@2x.png",
    days: "Days",
    x88: "/img/88@2x.png",
    rectangle59: "/img/rectangle-59@2x.png",
    rectangle60: "/img/rectangle-60@2x.png",
    hours: "Hours",
    x882: "/img/88-1@2x.png",
    rectangle61: "/img/rectangle-61@2x.png",
    rectangle62: "/img/rectangle-62@2x.png",
    minutes: "Minutes",
    x883: "/img/88-2@2x.png",
    rectangle63: "/img/rectangle-63@2x.png",
    rectangle64: "/img/rectangle-64@2x.png",
    seconds: "Seconds",
    x884: "/img/88-3@2x.png",
    time8GmtGlobalMetaverseTime: "time: 8 GMT (Global Metaverse Time )",
    frame522: "/img/frame-52-1@2x.png",
    ellipse16: "/img/ellipse-16-1@2x.png",
    faq: "/img/faq@2x.png",
    whenIsTheDrop: "When is the drop?",
    loremIpsumIsSimpl: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    name: "Will there be a comunity fund?",
    x4574: "/img/-@2x.png",
    whenIsTheDrop2: "When is the drop?",
    x4582: "/img/-@2x.svg",
    name2: "Will the price increase?",
    x4585: "/img/-@2x.png",
    name3: "Will there be a comunity fund?",
    x4588: "/img/-@2x.png",
    footer: "/img/footer@1x.png",
};

const iPhoneSE1Data = {
    xolodao: "/img/xolodao-1@2x.png",
    about: "/img/about-1@2x.png",
    roadmap: "/img/roadmap-4@2x.png",
    collection: "/img/collection-4@2x.png",
    dao: "/img/dao-1@2x.png",
    faq: "/img/faq-4@2x.png",
    frame143: "/img/frame-143-1@2x.png",
    xolodaoNft: "/img/xolodao-nft-2@2x.png",
    x20211126_115930: "/img/20211126-115930-2@2x.png",
    frame52: "/img/frame-52-4@2x.png",
    joinDiscord: "JOIN DISCORD",
    frame53: "/img/frame-53-2@2x.png",
    weAreNotJustAnot: <>We are not just another NFT Project!! We aim to achieve 3 main goals with our community.<br /><br />               1. Impact <br /><br />              2. Value <br /><br />             3. Connection <br />We choose the Xolo Dog to be our emblem as it is the guide between worlds. We aim to connect the physical and the digital world with our community and our actions. Read the Roadmap to find out and Join the XoloDAO</>,
    aboutUs: "/img/about-us-2@2x.png",
    overlapGroup: "/img/ellipse-16-4@2x.png",
    butterflyNft1: "/img/butterfly-nft-1-2@2x.png",
    xoloSugarSkull01: "/img/xolo-sugar-skull-01-4@2x.png",
    roadmap2: "/img/roadmap-3@2x.png",
    frame73: "/img/frame-73-2@2x.png",
    rectangle17: "/img/rectangle-17-2@2x.png",
    rectangle18: "/img/rectangle-18-2@2x.png",
    rectangle19: "/img/rectangle-19-2@2x.png",
    frame74: "/img/frame-74-2@2x.png",
    skull_Roadmap3: "/img/skull-roadmap-3-2@2x.png",
    frame76: "/img/frame-76-2@2x.png",
    xoloSugarSkull012: "/img/xolo-sugar-skull-01-5@2x.png",
    skull_Roadmap2: "/img/skull-roadmap-2-2@2x.png",
    frame75: "/img/frame-75-2@2x.png",
    skull_Roadmap4: "/img/skull-roadmap-4-2@2x.png",
    frame77: "/img/frame-77-2@2x.png",
    skull_Roadmap1: "/img/skull-roadmap-1-2@2x.png",
    collection2: "/img/collection-3@2x.png",
    weWillBeShowcasingSoonOurCollection: "/img/we-will-be-showcasing-soon-our-collection--join-our-discord-to-s-2@2x.png",
    dogs11: "/img/dogs1-1-2@2x.png",
    overlapGroup8: "/img/20211126-120014-2@2x.png",
    rectangle57: "/img/rectangle-57-2@2x.png",
    rectangle58: "/img/rectangle-58-2@2x.png",
    days: "Days",
    x88: "/img/88-8@2x.png",
    rectangle59: "/img/rectangle-59-2@2x.png",
    rectangle60: "/img/rectangle-60-2@2x.png",
    hours: "Hours",
    x882: "/img/88-9@2x.png",
    rectangle61: "/img/rectangle-61-2@2x.png",
    rectangle62: "/img/rectangle-62-2@2x.png",
    minutes: "Minutes",
    x883: "/img/88-10@2x.png",
    rectangle63: "/img/rectangle-63-2@2x.png",
    rectangle64: "/img/rectangle-64-2@2x.png",
    seconds: "Seconds",
    x884: "/img/88-11@2x.png",
    time8GmtGlobalMetaverseTime: "time: 8 GMT (Global Metaverse Time )",
    frame522: "/img/frame-52-5@2x.png",
    overlapGroup9: "/img/ellipse-16-5@2x.png",
    faq2: "/img/faq-3@2x.png",
    whenIsTheDrop: "When is the drop?",
    name: "Will there be a comunity fund?",
    x4614: "/img/-@2x.png",
    whenIsTheDrop2: "When is the drop?",
    name2: "Will the price increase?",
    x4625: "/img/-@2x.png",
    name3: "Will there be a comunity fund?",
    x4628: "/img/-@2x.png",
};

